site_name: Dynamic-Expressions
site_description: Build and evaluate dynamic expression trees
repo_url: https://github.com/1PaCHeK1/dynamic-expressions

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Concepts:
      - Architecture: concepts/architecture.md
      - Nodes: concepts/nodes.md
      - Visitors: concepts/visitors.md
      - Dispatcher: concepts/dispatcher.md
      - Context DSL: concepts/context-dsl.md
  - Advanced:
      - Custom nodes: advanced/custom-nodes.md
      - Middlewares: advanced/middlewares.md
      - Extensions overview: advanced/extensions/index.md
      - Cache extension: advanced/extensions/cache.md
  - Serialization:
      - Overview: serialization/index.md
      - Pydantic: serialization/pydantic.md
      - AST: serialization/ast.md
      - MsgSpec: serialization/msgspec.md
  - Cookbook:
      - Overview: cookbook/index.md
      - Basic: cookbook/basic.md
      - AST: cookbook/ast.md
      - AST + Context: cookbook/ast-context.md
      - Pydantic: cookbook/pydantic.md
      - Cache: cookbook/cache.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 2
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: false
            show_source: false
            show_root_heading: true
            show_root_toc_entry: false
            heading_level: 3
            docstring_section_style: table
            filters:
              - "!^_[^_]"
